stonith404/pingvin-share

- README.md
- docker-compose.yml
Instead of having the user restart pingvin-share after clamav is ready, this has the pingvin-share container not start until clamav has reported that it has fully started.
The README was changed as well.
> Docker compose changes

- frontend/src/components/share/modals/showCompletedReverseShareModal.tsx
- frontend/src/components/upload/CopyTextField.tsx
- frontend/src/components/upload/modals/showCompletedUploadModal.tsx
I added the possibility to copy the link just by clicking the text on the upload dialog, and I also added a small check icon when the copying is done. 
Tell me if you think something can be changed. I'll be happy to help for other things on this project, I've already used quite a lot TypeScript with React and also Vanilla NodeJS.
> feat: Adding the possibility of copying the link by clicking text and icons

- backend/src/share/dto/myShare.dto.ts
- backend/src/share/share.service.ts
- frontend/src/components/account/showShareInformationsModal.tsx
- frontend/src/pages/account/shares.tsx
- frontend/src/types/share.type.ts
The description of the share is now displayed out on the table of My Shares page and by clicking the new button Information, a Modal pops out, on which you can see multiples informations about the share, as shown below.
This Pull Request is related to the Issue #164 . Do not hesitate if you have any other ideas to add on the page, or if you want to modify these changes.
Images :
> feat: Adding more informations on My Shares page (table and modal)

- frontend/src/pages/account/reverseShares.tsx
Accessing shares that were made using a reverse share was quite long, copying the link, opening a new tab etc.. Now you can just click the share's ID and it opens the share.
> feat: Adding reverse shares' shares a clickable link

- backend/package.json
- frontend/package.json
- frontend/src/components/upload/modals/showCreateUploadModal.tsx
- package.json
The link input has now a default value, which is a random string.
I've kept the Generate link to make another one, if the user wants, or if he make a bad manipulation and have to generate another link.
> fix: set link default value to random

- backend/src/constants.ts
- backend/src/reverseShare/dto/reverseShare.dto.ts
- backend/src/share/dto/myShare.dto.ts
- frontend/src/components/account/showReverseShareLinkModal.tsx
- frontend/src/components/upload/CopyTextField.tsx
- frontend/src/pages/account/reverseShares.tsx
- frontend/src/pages/account/shares.tsx
- frontend/src/types/share.type.ts
I fetched the token from the backend and then I created the upload link, in order to display a link icon to copy the reverse share's link. I also created a modal to display the link when the context isn't secured. I added this because it was yet impossible to copy the link of the reverse share once it was created. Now you can copy it anytime.
Like this branch is child to the other PR, this may cause some other changes but it should normally works.
This is a preview :
> feat: Adding reverse share ability to copy the link

- frontend/src/i18n/translations/en-US.ts
- frontend/src/utils/toast.util.tsx
I added the translation of the success or error messages in the toast notifications because they were still hardcoded.
> fix: add translation in toast

- Dockerfile
This will change the docker OS to the newest version of Alpine Linux, therefore saving around 1/5th of the base ram usage (as mentioned in #241) compared to the image live on Docker hub. It also makes the image more secure by being up-to date.
Added the manual installation of curl, which fixed the issue of containers always showing up as unhealthy when built from the previous Dockerfile.
> fix(docker): Updated to newest version of alpine linux and fixed missing dependencies

- backend/src/file/file.controller.ts
- backend/src/file/file.service.ts
- backend/src/share/guard/shareOwner.guard.ts
- backend/src/share/share.controller.ts
- backend/src/share/share.service.ts
- frontend/src/components/upload/Dropzone.tsx
- frontend/src/components/upload/EditableUpload.tsx
- frontend/src/components/upload/FileList.tsx
- frontend/src/i18n/translations/en-US.ts
- frontend/src/i18n/translations/zh-CN.ts
- frontend/src/pages/account/shares.tsx
- frontend/src/pages/share/[shareId]/edit.tsx
- frontend/src/pages/upload/index.tsx
- frontend/src/services/share.service.ts
- frontend/src/types/File.type.ts
close #154 .
This is the effect achieved. Is there anything that needs to be adjusted in the process?
https://github.com/stonith404/pingvin-share/assets/30215105/08773c4c-12ab-4360-83fd-5c7f45de81a4
> feat: change file for exists share

- frontend/src/components/upload/modals/showCreateUploadModal.tsx
- frontend/src/i18n/translations/zh-CN.ts
I believe that after the administrator has set the maximum share expiration date in the sharing configuration of the system, users cannot check the Never expire option when creating a share.
->
So in this case, I've hidden the never expire option. (Maybe disabling is a better option?)
> chore(frontend/share): Displays the never expire checkbox if the system allows.

- backend/prisma/migrations/20240501154254_share_name_property/migration.sql
- backend/prisma/schema.prisma
- backend/src/reverseShare/dto/reverseShareTokenWithShares.ts
- backend/src/share/dto/createShare.dto.ts
- backend/src/share/dto/share.dto.ts
- backend/src/share/share.service.ts
- backend/test/newman-system-tests.json
- frontend/src/components/account/showShareInformationsModal.tsx
- frontend/src/components/upload/modals/showCreateUploadModal.tsx
- frontend/src/i18n/translations/en-US.ts
- frontend/src/pages/account/shares.tsx
- frontend/src/pages/share/[shareId]/index.tsx
- frontend/src/types/share.type.ts
This pull request adds the ability to define the name of a share.
It can be added while starting the upload:
And it will be displayed on the share page
...and on on the "My Shares" page:
Closes #430
> feat: add name property to share

- README.md
Update the docker compose start command to use the preferred way (since compose v2) as written here:
https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2
> README: Update docker command (v2)

- frontend/src/pages/admin/config/[category].tsx
I encountered an issue where the `appUrl` configuration would sometimes end with a trailing slash, such as `http://localhost:3000//s/c4MDgxM`. This PR addresses the issue by sanitizing the `appUrl` to ensure it does not end with a trailing slash before it is saved.
- Added `sanitizeUrl` function to remove the trailing slash from URLs.
- Updated `updateConfigVariable` function to sanitize `appUrl` before updating the state.
> chore: sanitize appUrl to remove trailing slash

- frontend/src/components/upload/modals/showCreateUploadModal.tsx
Fixes issue #500
**1. Use Gmail-esque email form, which automatically submit an email address when typing the , (comma) symbol, so users can manually type in multiple email addresses without clicking the dropdown box all the time.
2. Use type="email" in the email form, and let the browser auto-detects a valid email address, and submit the form if the browser allows to.**
**Implemented functionality where typing a comma followed by a space automatically submits the email address. This mirrors the common practice of typing out multiple items separated by commas.**
**After adding an email, if the user presses a comma followed by a space (e.g., exampleEmail@gmail.com, exampleEmail1@gmail.com), the email will be added to the recipient list and the input box will clear. This allows users to add …
> Worked on issue Feature Add email recipients more efficiently issue #500

- docker-compose-dev.yml
- docker-compose.yml
Very minor changes:
1. The compose `version` tag hasn't been necessary for a while now: https://docs.docker.com/compose/compose-file/04-version-and-name/
2. changed the default port in the compose file to the one provided by Next.js 14.2.3 when starting a new v.0.26.0 container
```
Attaching to pingvin-discord-pingvin-1
pingvin-discord-pingvin-1  | cp: can't create '/opt/app/frontend/public/img/favicon.ico': No such file or directory
pingvin-discord-pingvin-1  | cp: can't create directory '/opt/app/frontend/public/img/icons': No such file or directory
pingvin-discord-pingvin-1  | cp: can't create '/opt/app/frontend/public/img/logo.png': No such file or directory
pingvin-discord-pingvin-1  |   ▲ Next.js 14.2.3
pingvin-discord-pingvin-1  |   - Local:        http://localhost:3333 …
```
> Adjust docker compose

- backend/prisma/migrations/20240609145325_add_simplied_field_for_reverse_share/migration.sql
- backend/prisma/migrations/20240725141038_add_public_access_field_for_reverse_share/migration.sql
- backend/prisma/schema.prisma
- backend/src/file/guard/fileSecurity.guard.ts
- backend/src/reverseShare/dto/createReverseShare.dto.ts
- backend/src/reverseShare/dto/reverseShare.dto.ts
- backend/src/reverseShare/reverseShare.service.ts
- backend/src/share/dto/shareComplete.dto.ts
- backend/src/share/guard/shareSecurity.guard.ts
- backend/src/share/share.controller.ts
- backend/src/share/share.service.ts
- frontend/src/components/share/modals/showCreateReverseShareModal.tsx
- frontend/src/components/upload/modals/showCompletedUploadModal.tsx
- frontend/src/components/upload/modals/showCreateUploadModal.tsx
- frontend/src/i18n/translations/en-US.ts
- frontend/src/i18n/translations/zh-CN.ts
- frontend/src/pages/share/[shareId]/edit.tsx
- frontend/src/pages/share/[shareId]/index.tsx
- frontend/src/pages/upload/[reverseShareToken].tsx
- frontend/src/pages/upload/index.tsx
- frontend/src/services/share.service.ts
- frontend/src/types/share.type.ts
https://github.com/stonith404/pingvin-share/assets/30215105/27be9ed7-0c4b-4755-b6e4-d50b57ba41a6
The above is the effect currently achieved.
I have encountered some issues:
1. When creating a reverse share, if the recipient has already enabled email notifications, I would like to add a message in the "Share ready" dialog box to inform the uploader: "The system has notified the recipient to check the file. You can also copy the share link above to inform them." <br />This is my personal suggestion, and I would like to know if you think this prompt should be added. If you agree with this small prompt, perhaps we can expose the ReverseShare.sendEmailNotification field to determine the specific prompt text.
2. I believe that files shared via reverse sharing should only be visible to the …
> feat: add more options to reverse shares

- frontend/src/pages/index.tsx
PR fixes deadlink on "Get Started" button when allow registration is disabled. When registration is disabled, the "Get Started" button on the home page will now link to the signin page. #557
> Bug Fix: Get Started Button on Home Page not working when Sign-Up is disabled

- backend/prisma/seed/config.seed.ts
- backend/src/email/email.service.ts
- frontend/src/i18n/translations/en-US.ts
Thanks for this project! Some users were confused about their username when receiving invitations, so I added a placeholder in the invitation email to specify the username along with the password. 
Note: Translations will need to be updated to include this placeholder description.
Let me know if any further changes are needed.
> feat(email): add {email} placeholder to user invitation email

- docs/docs/setup/upgrading.md
the update guide mentions setting the API_URL environment variable, this is not necessary and has no effect since pm2 keeps the environment in the task and reuses it
> Remove env line and add comment about update-env

- backend/prisma/migrations/20241007181823_oauth_id_token/migration.sql
- backend/prisma/schema.prisma
- backend/prisma/seed/config.seed.ts
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.module.ts
- backend/src/auth/auth.service.ts
- backend/src/oauth/dto/oauthSignIn.dto.ts
- backend/src/oauth/oauth.module.ts
- backend/src/oauth/oauth.service.ts
- backend/src/oauth/provider/discord.provider.ts
- backend/src/oauth/provider/genericOidc.provider.ts
- backend/src/oauth/provider/github.provider.ts
- frontend/src/i18n/translations/de-DE.ts
- frontend/src/i18n/translations/en-US.ts
- frontend/src/services/auth.service.ts
* Fixes #598
Tested with Keycloak and the generic OpenID Connect provider configuration. 
It should be easy to extend the configurations of GitHub and Discord to support logout as well from here, but I never worked with those providers and don’t have a client configuration at hand for them. Feel free to test and extend.
> feat(oauth): Option to logout from OpenID Connect provider

- backend/src/auth/auth.service.ts
- docs/docs/setup/oauth2login.md
This is a small addition to #631. Apologies for not including it earlier.
Without it, the OpenID Connect provider shows a “You are now logged out – [Click here to go back to the application](https://pingvin-share.dev.eliasschneider.com)” confirmation page after logout. Adding the `post_logout_redirect_uri` parameter will cause the provider to perform the logout and immediately redirect back to Pingvin Share, reducing the number of user interactions and thereby streamlining the logout process.
This OpenID Connect feature is standardized [here](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RedirectionAfterLogout).
> fix(oauth): Add `post_logout_redirect_uri` to OAuth logout redirect URI

- frontend/src/i18n/translations/en-US.ts
we talked about addressing people in generic non-gender terms for the German translation, I looked through the English version first and noticed on gender-specific term assuming a user is "his"
> change his to their for describing user

- backend/prisma/seed/config.seed.ts
- frontend/src/components/upload/modals/showCreateUploadModal.tsx
- frontend/src/i18n/translations/en-US.ts
- frontend/src/i18n/translations/fr-FR.ts
- frontend/src/pages/upload/index.tsx
I'd like to be able to use a more robust share ID / share link when I share confidential files, regardless of password protection.
- Add share ID length to share > settings
- Use cryptographically secure RNG for IDs: I'm not a TS/JS expert, so I used a [snippet provided by Sentry](https://sentry.io/answers/generate-random-string-characters-in-javascript/) that should be relatively safe. `crypto.getRandomValues` is [well-supported](https://caniuse.com/getrandomvalues), and [does not require a secure context](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) (i.e. https), so it does not break when running locally/on a LAN without https.
- Use secure default value for IDs length: this topic is debated, but it is globally accepted that a 7 chars token is no longer safe …
> feat(share): add share ID length setting

- docs/docs/setup/oauth2login.md
While trying to set up your awesome project, I read through the docs and noticed that the links in `OAuth 2 Login Guide` are broken.
> feat(doc): fix links in oauth setup

- backend/src/file/file.controller.ts
- backend/src/file/file.service.ts
Hello! This is my first time contributing to an open source software, and it's also my first time working with nest, so please let me know if I'm not following best practices!
This PR fixes https://github.com/stonith404/pingvin-share/issues/708
This bug occurs because the ZIP file size exceeds the maximum buffer size that Node.js can handle in a single chunk.
I have removed the buffer conversion that was causing this bug, so that we directly return the readable stream from the storage service.
I have tested locally for shares larger than 4gb, and it doesn't crash now. The function `streamToUint8Array` is now unused, but I'm not sure if it will be used in the future, so I've left it in for now.
> bug(file): downloading zip exceeding 4gb crashes app

- docs/docs/help-out/contribute.md
- docs/docs/setup/integrations.md
- docs/docs/setup/upgrading.md
I changed "doc" to "docs" in `contribute.md` as I could only find the latter commit type in the commit history.
> docs: fix some typos

- .github/workflows/build-docker-image.yml
This is to (hopefully?) fix that the docker images have no labels. especially for ```"org.opencontainers.image.source":``` which is needed for [renovate bot](https://docs.renovatebot.com/modules/datasource/docker/) to be able to pull the Release notes for the image.
When running ```docker inspect ghcr.io/stonith404/pingvin-share:v1.10.1``` the image does not seem to have any labels, compared to for example ESPHome which has the following labels (for 2025.2.0):
```yaml
"Labels": {
"org.opencontainers.image.authors": "The ESPHome Authors",
"org.opencontainers.image.description": "ESPHome is a system to configure your microcontrollers by simple yet powerful configuration files and control them remotely through Home Automation systems",
"org.opencontainers.image.documentation": …
```
> Fix: Update build action and add labels to image for Renovate Bot support

- backend/prisma/seed/config.seed.ts
- backend/src/file/s3.service.ts
- frontend/src/i18n/translations/cs-CZ.ts
- frontend/src/i18n/translations/en-US.ts
Adds a S3 config option to disable upload checksums. Allows use of Backblaze B2 backend which does not support `x-amz-checksum-*` headers (rejects it as hard error).
Relates to https://github.com/stonith404/pingvin-share/issues/798, https://github.com/stonith404/pingvin-share/issues/788
Tested it against Backblaze B2 and its working.
> feat(s3): allow disabling upload checksum

- backend/prisma/seed/config.seed.ts
- config.example.yaml
- Change "in a hour" to "in an hour" in the default _Reset password message_ email template in files `config.example.yaml` and `config.seed.ts`.
- Change `... shared some files with you, view or download the files ...` to `... shared some files with you. You can view or download the files ...`. This adds more clarity on the specific call-to-action the recipient of the email.
> fix: Fix spelling mistake and add clarity in email template

- backend/package-lock.json
- backend/package.json
- backend/prisma/seed/config.seed.ts
- backend/src/app.module.ts
- backend/src/cache/cache.module.ts
- config.example.yaml
- frontend/src/components/admin/configuration/ConfigurationNavBar.tsx
- frontend/src/i18n/translations/en-US.ts
I am currently deploying Pingvin on kubernetes in high availability (multiple instance of the backend and frontend).
You are using cache to store [OIDC nouce](https://github.com/stonith404/pingvin-share/blob/3d1656688ed6fc15adf521959af77bc566753ef9/backend/src/oauth/provider/genericOidc.provider.ts#L131).
You are ussing memory cache.
This work well when you have only one instance of the backend.
But for obvious reason it break when you more that 1 instance.
If the oidc callback arrive to a different backend that pre OIDC request the nonce will not be available and therefore the backend will throw an error because it's nonce is undefined.
This PR introduce the possibility to enable/configure share Redis cache (disable by default).
Thank you for this amazing project :heart:
There will also …
> Feature: Backend/cache: Allow to use redis cache instead as memory
